workflows:
  my-workflow:
    name: donmex workflow
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - thezet@gmail.com
      scripts:
        - echo 'donmex done'