workflows:
  my-workflow:
    name: donmex workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      cancel_previous_builds: false
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/macos/**/*.ipa
    publishing:
      email:
        recipients:
          - thezet@gmail.com
      scripts:
        - echo 'donmex done'
