name: Flutter Podfile generation 15

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.0'   # specify the Flutter version you're using

    - name: Generate iOS Podfile
      run: |
        echo "platform :ios, '12.0'" > ios/Podfile
        echo "" >> ios/Podfile
        echo "target 'Runner' do" >> ios/Podfile
        echo "  use_frameworks!" >> ios/Podfile
        echo "  use_modular_headers!" >> ios/Podfile
        echo "" >> ios/Podfile
        echo "  # Pods for Runner" >> ios/Podfile
        echo "  pod 'audio_session', '~> 1.0.0'" >> ios/Podfile  # replace '1.0.0' with your desired version
        echo "end" >> ios/Podfile


    - name: Install Pods
      run: |
        cd ios
        pod install
        
    - name: Push Podfile
      run: |
        git config --global user.name 'thezet13'
        git config --global user.email 'thezet@gmail.com'
        git add ios/Podfile
        git commit -m "Add Podfile"
        git push
