name: Flutter Podfile generation 15

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.0'   # specify the Flutter version you're using

    - name: Generate iOS Podfile
    - name: Generate Podfile
      run: |
        echo "platform :ios, '11.0'" > ios/Podfile
        echo "" >> ios/Podfile
        echo "target 'Runner' do" >> ios/Podfile
        echo "  use_frameworks!" >> ios/Podfile
        echo "  use_modular_headers!" >> ios/Podfile
        echo "" >> ios/Podfile
        echo "  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))" >> ios/Podfile
        echo "end" >> ios/Podfile

    - name: Push Podfile
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'
        git add ios/Podfile
        git commit -m "Add Podfile"
        git push

    - name: Run tests
      run: flutter test
